/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/refresh-mvs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Mvs */
        post: operations["refresh_mvs_admin_refresh_mvs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Suppliers */
        get: operations["list_suppliers_suppliers_get"];
        put?: never;
        /** Create Supplier */
        post: operations["create_supplier_suppliers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suppliers/{supplier_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Supplier */
        get: operations["get_supplier_suppliers__supplier_id__get"];
        put?: never;
        post?: never;
        /** Soft Delete Supplier */
        delete: operations["soft_delete_supplier_suppliers__supplier_id__delete"];
        options?: never;
        head?: never;
        /** Update Supplier */
        patch: operations["update_supplier_suppliers__supplier_id__patch"];
        trace?: never;
    };
    "/suppliers/{supplier_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Supplier */
        post: operations["restore_supplier_suppliers__supplier_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certificates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Certificates */
        get: operations["list_certificates_certificates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certificates/{cert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Certificate */
        get: operations["get_certificate_certificates__cert_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contracts */
        get: operations["list_contracts_contracts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{contract_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contract */
        get: operations["get_contract_contracts__contract_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-inputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Daily Inputs */
        get: operations["list_daily_inputs_daily_inputs_get"];
        put?: never;
        /** Create Daily Input */
        post: operations["create_daily_input_daily_inputs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-inputs/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Count Daily Inputs */
        get: operations["count_daily_inputs_daily_inputs_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-inputs/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Daily Input */
        get: operations["get_daily_input_daily_inputs__entry_id__get"];
        put?: never;
        post?: never;
        /** Soft Delete Daily Input */
        delete: operations["soft_delete_daily_input_daily_inputs__entry_id__delete"];
        options?: never;
        head?: never;
        /** Update Daily Input */
        patch: operations["update_daily_input_daily_inputs__entry_id__patch"];
        trace?: never;
    };
    "/daily-inputs/{entry_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Daily Input */
        post: operations["restore_daily_input_daily_inputs__entry_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-production": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Daily Production */
        get: operations["list_daily_production_daily_production_get"];
        put?: never;
        /** Create Daily Production */
        post: operations["create_daily_production_daily_production_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-production/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Count Daily Production */
        get: operations["count_daily_production_daily_production_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-production/{prod_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Daily Production */
        get: operations["get_daily_production_daily_production__prod_id__get"];
        put?: never;
        post?: never;
        /** Soft Delete Daily Production */
        delete: operations["soft_delete_daily_production_daily_production__prod_id__delete"];
        options?: never;
        head?: never;
        /** Update Daily Production */
        patch: operations["update_daily_production_daily_production__prod_id__patch"];
        trace?: never;
    };
    "/daily-production/{prod_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Daily Production */
        post: operations["restore_daily_production_daily_production__prod_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/mass-balance/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mass Balance Daily */
        get: operations["mass_balance_daily_reports_mass_balance_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/mass-balance/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mass Balance Monthly */
        get: operations["mass_balance_monthly_reports_mass_balance_monthly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/by-supplier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** By Supplier */
        get: operations["by_supplier_reports_by_supplier_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/closure-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Closure Status */
        get: operations["closure_status_reports_closure_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BySupplierRow */
        BySupplierRow: {
            /** Supplier Id */
            supplier_id: number;
            /** Supplier Code */
            supplier_code: string;
            /** Supplier Name */
            supplier_name: string;
            /** Total Input Kg */
            total_input_kg: string;
            /** Entries */
            entries: number;
            /** Days */
            days: number;
        };
        /** CertificateRead */
        CertificateRead: {
            /** Cert Number */
            cert_number: string;
            /**
             * Scheme
             * @default ISCC EU
             */
            scheme: string;
            /**
             * Status
             * @default active
             * @enum {string}
             */
            status: "active" | "expired" | "revoked" | "placeholder";
            /** Issued At */
            issued_at?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /**
             * Is Placeholder
             * @default false
             */
            is_placeholder: boolean;
            /** Document Url */
            document_url?: string | null;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at?: string | null;
        };
        /** ClosureStatusRow */
        ClosureStatusRow: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Input Total Kg */
            input_total_kg?: string | null;
            /** Output Total Kg */
            output_total_kg?: string | null;
            /** Closure Diff Pct */
            closure_diff_pct?: string | null;
            /** Bucket */
            bucket: string;
        };
        /** ContractRead */
        ContractRead: {
            /** Code */
            code: string;
            /** Supplier Id */
            supplier_id?: number | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Total Kg Committed */
            total_kg_committed?: string | null;
            /**
             * Is Placeholder
             * @default false
             */
            is_placeholder: boolean;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at?: string | null;
        };
        /** DailyInputCreate */
        DailyInputCreate: {
            /**
             * Entry Date
             * Format: date
             */
            entry_date: string;
            /** Entry Time */
            entry_time?: string | null;
            /** Supplier Id */
            supplier_id: number;
            /** Certificate Id */
            certificate_id?: number | null;
            /** Contract Id */
            contract_id?: number | null;
            /** Ersv Number */
            ersv_number?: string | null;
            /**
             * Car Kg
             * @default 0
             */
            car_kg: number | string;
            /**
             * Truck Kg
             * @default 0
             */
            truck_kg: number | string;
            /**
             * Special Kg
             * @default 0
             */
            special_kg: number | string;
            /** Theor Veg Pct */
            theor_veg_pct?: number | string | null;
            /** Manuf Veg Pct */
            manuf_veg_pct?: number | string | null;
            /** C14 Analysis */
            c14_analysis?: string | null;
            /** C14 Value */
            c14_value?: number | string | null;
            /** Notes */
            notes?: string | null;
            /** Source File */
            source_file?: string | null;
            /** Source Row */
            source_row?: number | null;
        };
        /** DailyInputRead */
        DailyInputRead: {
            /**
             * Entry Date
             * Format: date
             */
            entry_date: string;
            /** Entry Time */
            entry_time?: string | null;
            /** Supplier Id */
            supplier_id: number;
            /** Certificate Id */
            certificate_id?: number | null;
            /** Contract Id */
            contract_id?: number | null;
            /** Ersv Number */
            ersv_number?: string | null;
            /**
             * Car Kg
             * @default 0
             */
            car_kg: string;
            /**
             * Truck Kg
             * @default 0
             */
            truck_kg: string;
            /**
             * Special Kg
             * @default 0
             */
            special_kg: string;
            /** Theor Veg Pct */
            theor_veg_pct?: string | null;
            /** Manuf Veg Pct */
            manuf_veg_pct?: string | null;
            /** C14 Analysis */
            c14_analysis?: string | null;
            /** C14 Value */
            c14_value?: string | null;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
            /** Total Input Kg */
            total_input_kg: string;
            /** Source File */
            source_file?: string | null;
            /** Source Row */
            source_row?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at?: string | null;
            /** Created By */
            created_by?: number | null;
            /** Updated By */
            updated_by?: number | null;
        };
        /** DailyInputUpdate */
        DailyInputUpdate: {
            /** Entry Date */
            entry_date?: string | null;
            /** Entry Time */
            entry_time?: string | null;
            /** Supplier Id */
            supplier_id?: number | null;
            /** Certificate Id */
            certificate_id?: number | null;
            /** Contract Id */
            contract_id?: number | null;
            /** Ersv Number */
            ersv_number?: string | null;
            /** Car Kg */
            car_kg?: number | string | null;
            /** Truck Kg */
            truck_kg?: number | string | null;
            /** Special Kg */
            special_kg?: number | string | null;
            /** Theor Veg Pct */
            theor_veg_pct?: number | string | null;
            /** Manuf Veg Pct */
            manuf_veg_pct?: number | string | null;
            /** C14 Analysis */
            c14_analysis?: string | null;
            /** C14 Value */
            c14_value?: number | string | null;
            /** Notes */
            notes?: string | null;
        };
        /** DailyProductionCreate */
        DailyProductionCreate: {
            /**
             * Prod Date
             * Format: date
             */
            prod_date: string;
            /** Kg To Production */
            kg_to_production?: number | string | null;
            /** Eu Prod Kg */
            eu_prod_kg?: number | string | null;
            /** Plus Prod Kg */
            plus_prod_kg?: number | string | null;
            /** Carbon Black Kg */
            carbon_black_kg?: number | string | null;
            /** Metal Scrap Kg */
            metal_scrap_kg?: number | string | null;
            /** H2O Kg */
            h2o_kg?: number | string | null;
            /** Gas Syngas Kg */
            gas_syngas_kg?: number | string | null;
            /** Losses Kg */
            losses_kg?: number | string | null;
            /** Output Eu Kg */
            output_eu_kg?: number | string | null;
            /** Contract Ref */
            contract_ref?: string | null;
            /** Pos Number */
            pos_number?: string | null;
            /** Notes */
            notes?: string | null;
            /** Source File */
            source_file?: string | null;
            /** Source Row */
            source_row?: number | null;
        };
        /** DailyProductionRead */
        DailyProductionRead: {
            /**
             * Prod Date
             * Format: date
             */
            prod_date: string;
            /** Kg To Production */
            kg_to_production?: string | null;
            /** Eu Prod Kg */
            eu_prod_kg?: string | null;
            /** Plus Prod Kg */
            plus_prod_kg?: string | null;
            /** Carbon Black Kg */
            carbon_black_kg?: string | null;
            /** Metal Scrap Kg */
            metal_scrap_kg?: string | null;
            /** H2O Kg */
            h2o_kg?: string | null;
            /** Gas Syngas Kg */
            gas_syngas_kg?: string | null;
            /** Losses Kg */
            losses_kg?: string | null;
            /** Output Eu Kg */
            output_eu_kg?: string | null;
            /** Contract Ref */
            contract_ref?: string | null;
            /** Pos Number */
            pos_number?: string | null;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
            /** Source File */
            source_file?: string | null;
            /** Source Row */
            source_row?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at?: string | null;
            /** Created By */
            created_by?: number | null;
            /** Updated By */
            updated_by?: number | null;
        };
        /** DailyProductionUpdate */
        DailyProductionUpdate: {
            /** Kg To Production */
            kg_to_production?: number | string | null;
            /** Eu Prod Kg */
            eu_prod_kg?: number | string | null;
            /** Plus Prod Kg */
            plus_prod_kg?: number | string | null;
            /** Carbon Black Kg */
            carbon_black_kg?: number | string | null;
            /** Metal Scrap Kg */
            metal_scrap_kg?: number | string | null;
            /** H2O Kg */
            h2o_kg?: number | string | null;
            /** Gas Syngas Kg */
            gas_syngas_kg?: number | string | null;
            /** Losses Kg */
            losses_kg?: number | string | null;
            /** Output Eu Kg */
            output_eu_kg?: number | string | null;
            /** Contract Ref */
            contract_ref?: string | null;
            /** Pos Number */
            pos_number?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MassBalanceDailyRow */
        MassBalanceDailyRow: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Input Total Kg */
            input_total_kg?: string | null;
            /** Kg To Production */
            kg_to_production?: string | null;
            /** Eu Prod Kg */
            eu_prod_kg?: string | null;
            /** Plus Prod Kg */
            plus_prod_kg?: string | null;
            /** Carbon Black Kg */
            carbon_black_kg?: string | null;
            /** Metal Scrap Kg */
            metal_scrap_kg?: string | null;
            /** H2O Kg */
            h2o_kg?: string | null;
            /** Gas Syngas Kg */
            gas_syngas_kg?: string | null;
            /** Losses Kg */
            losses_kg?: string | null;
            /** Output Eu Kg */
            output_eu_kg?: string | null;
            /** Output Total Kg */
            output_total_kg?: string | null;
            /** Closure Diff Pct */
            closure_diff_pct?: string | null;
        };
        /** MassBalanceMonthlyRow */
        MassBalanceMonthlyRow: {
            /**
             * Month
             * Format: date
             */
            month: string;
            /** Input Total Kg */
            input_total_kg?: string | null;
            /** Eu Prod Kg */
            eu_prod_kg?: string | null;
            /** Plus Prod Kg */
            plus_prod_kg?: string | null;
            /** Carbon Black Kg */
            carbon_black_kg?: string | null;
            /** Metal Scrap Kg */
            metal_scrap_kg?: string | null;
            /** H2O Kg */
            h2o_kg?: string | null;
            /** Gas Syngas Kg */
            gas_syngas_kg?: string | null;
            /** Losses Kg */
            losses_kg?: string | null;
            /** Output Eu Kg */
            output_eu_kg?: string | null;
            /** Output Total Kg */
            output_total_kg?: string | null;
            /** Closure Diff Pct */
            closure_diff_pct?: string | null;
        };
        /** SupplierCreate */
        SupplierCreate: {
            /** Name */
            name: string;
            /** Code */
            code: string;
            /** Country */
            country?: string | null;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /**
             * Is Aggregate
             * @default false
             */
            is_aggregate: boolean;
            /** Notes */
            notes?: string | null;
        };
        /** SupplierRead */
        SupplierRead: {
            /** Name */
            name: string;
            /** Code */
            code: string;
            /** Country */
            country?: string | null;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /**
             * Is Aggregate
             * @default false
             */
            is_aggregate: boolean;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at?: string | null;
        };
        /** SupplierUpdate */
        SupplierUpdate: {
            /** Name */
            name?: string | null;
            /** Code */
            code?: string | null;
            /** Country */
            country?: string | null;
            /** Active */
            active?: boolean | null;
            /** Is Aggregate */
            is_aggregate?: boolean | null;
            /** Notes */
            notes?: string | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserRead */
        UserRead: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name?: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "operator" | "viewer" | "certifier";
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    refresh_mvs_admin_refresh_mvs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
    };
    list_suppliers_suppliers_get: {
        parameters: {
            query?: {
                /** @description Filter active=true */
                active_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_supplier_suppliers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_supplier_suppliers__supplier_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supplier_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    soft_delete_supplier_suppliers__supplier_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supplier_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_supplier_suppliers__supplier_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supplier_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_supplier_suppliers__supplier_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supplier_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_certificates_certificates_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_certificate_certificates__cert_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_contracts_contracts_get: {
        parameters: {
            query?: {
                supplier_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contract_contracts__contract_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_daily_inputs_daily_inputs_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                supplier_id?: number | null;
                include_deleted?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyInputRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_daily_input_daily_inputs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DailyInputCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyInputRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    count_daily_inputs_daily_inputs_count_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                supplier_id?: number | null;
                include_deleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_daily_input_daily_inputs__entry_id__get: {
        parameters: {
            query?: {
                include_deleted?: boolean;
            };
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyInputRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    soft_delete_daily_input_daily_inputs__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_daily_input_daily_inputs__entry_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DailyInputUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyInputRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_daily_input_daily_inputs__entry_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyInputRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_daily_production_daily_production_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                include_deleted?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyProductionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_daily_production_daily_production_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DailyProductionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyProductionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    count_daily_production_daily_production_count_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                include_deleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_daily_production_daily_production__prod_id__get: {
        parameters: {
            query?: {
                include_deleted?: boolean;
            };
            header?: never;
            path: {
                prod_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyProductionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    soft_delete_daily_production_daily_production__prod_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prod_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_daily_production_daily_production__prod_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prod_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DailyProductionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyProductionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_daily_production_daily_production__prod_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prod_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyProductionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mass_balance_daily_reports_mass_balance_daily_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MassBalanceDailyRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mass_balance_monthly_reports_mass_balance_monthly_get: {
        parameters: {
            query?: {
                /** @description month start (e.g., 2025-01-01) */
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MassBalanceMonthlyRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    by_supplier_reports_by_supplier_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BySupplierRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    closure_status_reports_closure_status_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClosureStatusRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
